/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GABS
 */
public class frmMain extends javax.swing.JFrame {

   String nol_jam = "";
    String nol_menit ="";
    String nol_detik ="";

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        SetTanggal();
        SetJam();
        selectData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();
        waktu = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNIS = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rdPerempuan = new javax.swing.JRadioButton();
        rdLaki = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtKelas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        print = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 7));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM BIODATA SISWA SMK TELKOM");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(40, 20, 470, 28);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("The Real Informatic Schools");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 60, 210, 17);

        tgl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tgl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(tgl);
        tgl.setBounds(680, 30, 140, 30);

        waktu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        waktu.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(waktu);
        waktu.setBounds(690, 70, 130, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 910, 120);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ISIAN DATA SISWA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Alamat");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 330, 60, 14);
        jPanel1.add(txtNIS);
        txtNIS.setBounds(10, 50, 290, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Jenis Kelamin");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 150, 110, 14);
        jPanel1.add(txtNama);
        txtNama.setBounds(10, 110, 290, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("NIS");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 30, 40, 14);

        buttonGroup1.add(rdPerempuan);
        rdPerempuan.setText("Perempuan");
        jPanel1.add(rdPerempuan);
        rdPerempuan.setBounds(190, 170, 110, 30);

        buttonGroup1.add(rdLaki);
        rdLaki.setText("Laki-laki");
        jPanel1.add(rdLaki);
        rdLaki.setBounds(10, 170, 100, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Nama");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 90, 60, 14);
        jPanel1.add(txtKelas);
        txtKelas.setBounds(10, 230, 290, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Kelas");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 210, 60, 14);
        jPanel1.add(txtEmail);
        txtEmail.setBounds(10, 290, 290, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Email");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 270, 60, 14);

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 350, 290, 96);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 130, 360, 460);

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));
        jPanel3.setLayout(null);

        btnEdit.setBackground(new java.awt.Color(102, 102, 102));
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel3.add(btnEdit);
        btnEdit.setBounds(330, 10, 80, 30);

        btnAdd.setBackground(new java.awt.Color(102, 102, 102));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Save");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel3.add(btnAdd);
        btnAdd.setBounds(0, 10, 80, 30);

        Reset.setBackground(new java.awt.Color(102, 102, 102));
        Reset.setForeground(new java.awt.Color(255, 255, 255));
        Reset.setText("Clear");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        jPanel3.add(Reset);
        Reset.setBounds(160, 10, 80, 30);

        btnDelete.setBackground(new java.awt.Color(102, 102, 102));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btnDelete);
        btnDelete.setBounds(80, 10, 80, 30);

        btnRefresh.setBackground(new java.awt.Color(102, 102, 102));
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel3.add(btnRefresh);
        btnRefresh.setBounds(240, 10, 90, 30);

        print.setBackground(new java.awt.Color(102, 102, 102));
        print.setForeground(new java.awt.Color(255, 255, 255));
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel3.add(print);
        print.setBounds(410, 10, 80, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(390, 130, 510, 50);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setLayout(null);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "NamaSiswa", "JenisKelamin", "Kelas", "Email", "Alamat"
            }
        ));
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblData);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(30, 0, 452, 380);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(390, 190, 510, 400);

        setBounds(0, 0, 921, 641);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if ("".equals(txtNIS.getText()) || "".equals(txtNama.getText()) || 
            "".equals(txtKelas.getText()) || "".equals(txtEmail.getText()) || 
            "".equals(txtAlamat.getText()))
        {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }
    
    else
    {
        String JK = "";
        if (rdLaki.isSelected())
        {
            JK = "L";
        }
        else
        {
            JK = "P";
        }
        
        String SQL = "INSERT INTO t_siswa (NIS,NamaSiswa,JenisKelamin,Kelas,Email,Alamat) "
                + "VALUES('"+txtNIS.getText()+"','"+txtNama.getText()+"','"+JK+"',"
                + "'"+txtKelas.getText()+"','"+txtEmail.getText()+"','"+txtAlamat.getText()+"')";
        int status = KoneksiDB.execute(SQL);
        if (status == 1)
        {
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            selectData();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Sukses", JOptionPane.WARNING_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
       int baris = tblData.getSelectedRow();
        
        if (baris != -1)
        {
            String NIS = tblData.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM t_siswa WHERE NIS='"+NIS+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1)
            {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
        
        else
        {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
         txtNama.setText("");
        txtNIS.setText("");
        txtKelas.setText("");
        buttonGroup1.clearSelection();
        txtEmail.setText("");
        txtAlamat.setText("");
    }//GEN-LAST:event_ResetActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
         if ("".equals(txtNIS.getText()) ||"".equals(txtNama.getText()) || "".equals(txtKelas.getText()) ||"".equals(txtEmail.getText())||"".equals(txtAlamat.getText()))
        {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
                String JK = "";
                
                if (rdLaki.isSelected())
            {
                JK = "L";
            } else{
                JK = "P";
         }
         
        String SQL = "UPDATE t_siswa SET"
                + "NamaSiswa='"+txtNama.getText()+"',"
                + "JenisKelamin='"+JK+"',"
                + "Kelas='"+txtKelas.getText()+"',"
                + "Email='"+txtEmail.getText()+"',"
                + "Alamat='"+txtAlamat.getText()+"' WHERE NIS='"+txtNIS.getText()+"'"; 
        int status = KoneksiDB.execute(SQL);
        if (status == 1)
        {
            JOptionPane.showMessageDialog(this, "Data berhasil diupdate", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Data gagal diupdate", "Gagal", JOptionPane.WARNING_MESSAGE);
        }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        // TODO add your handling code here:
        int baris = tblData.getSelectedRow();
        if (baris != -1) {
            txtNIS.setText(tblData.getValueAt(baris,0).toString());
            txtNama.setText(tblData.getValueAt(baris,1).toString());
            if ("Laki-laki".equals(tblData.getValueAt(baris,2).toString())) {
                rdLaki.setSelected(true);
            }else{
                rdPerempuan.setSelected(true);
            }
            txtKelas.setText(tblData.getValueAt(baris,3).toString());
            txtEmail.setText(tblData.getValueAt(baris,4).toString());
            txtAlamat.setText(tblData.getValueAt(baris,5).toString());
        }
    }//GEN-LAST:event_tblDataMouseClicked

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed

    MessageFormat header = new MessageFormat("Biodata Siswa SMK Telkom Malang");
        MessageFormat footer = new MessageFormat("Page {0, number, integer}     ");
        try {
            tblData.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
            
        }catch(java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
            
        }






        // TODO add your handling code here:
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reset;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton print;
    private javax.swing.JRadioButton rdLaki;
    private javax.swing.JRadioButton rdPerempuan;
    private javax.swing.JTable tblData;
    private javax.swing.JLabel tgl;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtKelas;
    private javax.swing.JTextField txtNIS;
    private javax.swing.JTextField txtNama;
    private javax.swing.JLabel waktu;
    // End of variables declaration//GEN-END:variables

    public void selectData() {
    String kolom[] = {"NIS","NamaSiswa","JenisKelamin","Kelas","Email","Alamat"};
    DefaultTableModel dtm = new DefaultTableModel(null,kolom);
    String SQL = "SELECT * FROM t_siswa";
    ResultSet rs = KoneksiDB.executeQuery(SQL);
    try {
        while (rs.next()){
        String NIS = rs.getString(1);
        String NamaSiswa = rs.getString(2);
        String JenisKelamin = "";
            if ("L".equals(rs.getString(3))) {
                JenisKelamin = "Laki-laki";
            }else{
                JenisKelamin = "Perempuan";
            }
            String Kelas = rs.getString(4);
            String Email = rs.getString(5);
            String Alamat = rs.getString(6);
            String data[] = {NIS,NamaSiswa,JenisKelamin,Kelas,Email,Alamat};
            dtm.addRow(data);
        }   
    } catch (SQLException ex){
        Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE,null,ex);
    }
    tblData.setModel(dtm);
    }
   

 public void SetTanggal(){
    java.util.Date skrg = new java.util.Date();
    java.text.SimpleDateFormat kal = new
    java.text.SimpleDateFormat ("dd/MM/yyyy");
    tgl.setText(kal.format(skrg));
    }
      public void SetJam(){
        ActionListener taskPerformer = new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();               
                if(nilai_jam <= 9){
                    nol_jam = "0";
                    
                }
                if(nilai_menit <= 9){
                    nol_menit = "0";
                }
                if(nilai_detik <= 9){
                    nol_detik = "0";
                }
                
                 String jam = nol_jam +Integer.toString(nilai_jam);
                  String menit = nol_menit +Integer.toString(nilai_menit);
                   String detik = nol_detik +Integer.toString(nilai_detik);
                   waktu.setText("Jam "+jam+ ":" +menit+ ":" +detik);
                   
            }
        
        };
        new Timer(100, taskPerformer).start();
    }
}
